// Generated by gencpp from file object_detector/detector.msg
// DO NOT EDIT!


#ifndef OBJECT_DETECTOR_MESSAGE_DETECTOR_H
#define OBJECT_DETECTOR_MESSAGE_DETECTOR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/ColorRGBA.h>

namespace object_detector
{
template <class ContainerAllocator>
struct detector_
{
  typedef detector_<ContainerAllocator> Type;

  detector_()
    : color()  {
    }
  detector_(const ContainerAllocator& _alloc)
    : color(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::ColorRGBA_<ContainerAllocator>  _color_type;
  _color_type color;





  typedef boost::shared_ptr< ::object_detector::detector_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::object_detector::detector_<ContainerAllocator> const> ConstPtr;

}; // struct detector_

typedef ::object_detector::detector_<std::allocator<void> > detector;

typedef boost::shared_ptr< ::object_detector::detector > detectorPtr;
typedef boost::shared_ptr< ::object_detector::detector const> detectorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::object_detector::detector_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::object_detector::detector_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace object_detector

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'object_detector': ['/home/turtlebot/Documents/catkin_ws/src/object_detector/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::object_detector::detector_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::object_detector::detector_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_detector::detector_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_detector::detector_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_detector::detector_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_detector::detector_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::object_detector::detector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3e04b62b1b39cd97e873789f0bb130e7";
  }

  static const char* value(const ::object_detector::detector_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3e04b62b1b39cd97ULL;
  static const uint64_t static_value2 = 0xe873789f0bb130e7ULL;
};

template<class ContainerAllocator>
struct DataType< ::object_detector::detector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "object_detector/detector";
  }

  static const char* value(const ::object_detector::detector_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::object_detector::detector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/ColorRGBA color\n\
\n\
================================================================================\n\
MSG: std_msgs/ColorRGBA\n\
float32 r\n\
float32 g\n\
float32 b\n\
float32 a\n\
";
  }

  static const char* value(const ::object_detector::detector_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::object_detector::detector_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.color);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct detector_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::object_detector::detector_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::object_detector::detector_<ContainerAllocator>& v)
  {
    s << indent << "color: ";
    s << std::endl;
    Printer< ::std_msgs::ColorRGBA_<ContainerAllocator> >::stream(s, indent + "  ", v.color);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OBJECT_DETECTOR_MESSAGE_DETECTOR_H
